name: Omnihost

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - add-gitops-deployments

jobs:
  omnihost:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: make output dirs
        run: mkdir output && mkdir output/www output/gemini
      - name: process-pages
        uses: actions/setup-python@v4
        with: 
          python-version: "3.10"
      - run: |
          pip install omnihost
          omnihost -i ${{ github.workspace }}/brett-xyz \
            -s ${{ github.workspace }}/css \
            -w ${{ github.workspace }}/output/www \
            -o ${{ github.workspace }}/output/gemini
      - name: prepare-artifact
        run: zip omnihost_output.zip ${{ github.workspace }}/output
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: omnihost_output
          path: omnihost_output.zip
          retention-days: 1
